// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Rig.Storage
{
    [EntityFrameworkInternal]
    public partial class CallGraphNodeCallEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Rig.Storage.CallGraphNodeCallEntity",
                typeof(CallGraphNodeCallEntity),
                baseEntityType,
                propertyCount: 5,
                keyCount: 1);

            var runId = runtimeEntityType.AddProperty(
                "RunId",
                typeof(string),
                propertyInfo: typeof(CallGraphNodeCallEntity).GetProperty("RunId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeCallEntity).GetField("<RunId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);

            var graphIndex = runtimeEntityType.AddProperty(
                "GraphIndex",
                typeof(int),
                propertyInfo: typeof(CallGraphNodeCallEntity).GetProperty("GraphIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeCallEntity).GetField("<GraphIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var nodeIndex = runtimeEntityType.AddProperty(
                "NodeIndex",
                typeof(int),
                propertyInfo: typeof(CallGraphNodeCallEntity).GetProperty("NodeIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeCallEntity).GetField("<NodeIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var callIndex = runtimeEntityType.AddProperty(
                "CallIndex",
                typeof(int),
                propertyInfo: typeof(CallGraphNodeCallEntity).GetProperty("CallIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeCallEntity).GetField("<CallIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var targetSymbol = runtimeEntityType.AddProperty(
                "TargetSymbol",
                typeof(string),
                propertyInfo: typeof(CallGraphNodeCallEntity).GetProperty("TargetSymbol", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeCallEntity).GetField("<TargetSymbol>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var key = runtimeEntityType.AddKey(
                new[] { runId, graphIndex, nodeIndex, callIndex });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "callgraph_node_calls");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
