// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Rig.Storage
{
    [EntityFrameworkInternal]
    public partial class CallGraphNodeEffectEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Rig.Storage.CallGraphNodeEffectEntity",
                typeof(CallGraphNodeEffectEntity),
                baseEntityType,
                propertyCount: 5,
                unnamedIndexCount: 1,
                keyCount: 1);

            var runId = runtimeEntityType.AddProperty(
                "RunId",
                typeof(string),
                propertyInfo: typeof(CallGraphNodeEffectEntity).GetProperty("RunId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeEffectEntity).GetField("<RunId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);

            var graphIndex = runtimeEntityType.AddProperty(
                "GraphIndex",
                typeof(int),
                propertyInfo: typeof(CallGraphNodeEffectEntity).GetProperty("GraphIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeEffectEntity).GetField("<GraphIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var nodeIndex = runtimeEntityType.AddProperty(
                "NodeIndex",
                typeof(int),
                propertyInfo: typeof(CallGraphNodeEffectEntity).GetProperty("NodeIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeEffectEntity).GetField("<NodeIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var linkIndex = runtimeEntityType.AddProperty(
                "LinkIndex",
                typeof(int),
                propertyInfo: typeof(CallGraphNodeEffectEntity).GetProperty("LinkIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeEffectEntity).GetField("<LinkIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var effectIndex = runtimeEntityType.AddProperty(
                "EffectIndex",
                typeof(int),
                propertyInfo: typeof(CallGraphNodeEffectEntity).GetProperty("EffectIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallGraphNodeEffectEntity).GetField("<EffectIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var key = runtimeEntityType.AddKey(
                new[] { runId, graphIndex, nodeIndex, linkIndex });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { runId, graphIndex, nodeIndex });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "callgraph_node_effects");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
