// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Rig.Storage
{
    public partial class RigDbContextModel
    {
        private RigDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("2752e30a-3597-4692-aad2-8ef1eed3f346"), entityTypeCount: 13)
        {
        }

        partial void Initialize()
        {
            var callGraphBoundaryCallEntity = CallGraphBoundaryCallEntityEntityType.Create(this);
            var callGraphEntity = CallGraphEntityEntityType.Create(this);
            var callGraphNodeCallEntity = CallGraphNodeCallEntityEntityType.Create(this);
            var callGraphNodeEffectEntity = CallGraphNodeEffectEntityEntityType.Create(this);
            var callGraphNodeEntity = CallGraphNodeEntityEntityType.Create(this);
            var diRegistrationEntity = DiRegistrationEntityEntityType.Create(this);
            var effectEntity = EffectEntityEntityType.Create(this);
            var effectObservationEntity = EffectObservationEntityEntityType.Create(this);
            var entryPointEntity = EntryPointEntityEntityType.Create(this);
            var invocationObservationEntity = InvocationObservationEntityEntityType.Create(this);
            var methodObservationEntity = MethodObservationEntityEntityType.Create(this);
            var runEntity = RunEntityEntityType.Create(this);
            var sourceFileEntity = SourceFileEntityEntityType.Create(this);

            CallGraphBoundaryCallEntityEntityType.CreateAnnotations(callGraphBoundaryCallEntity);
            CallGraphEntityEntityType.CreateAnnotations(callGraphEntity);
            CallGraphNodeCallEntityEntityType.CreateAnnotations(callGraphNodeCallEntity);
            CallGraphNodeEffectEntityEntityType.CreateAnnotations(callGraphNodeEffectEntity);
            CallGraphNodeEntityEntityType.CreateAnnotations(callGraphNodeEntity);
            DiRegistrationEntityEntityType.CreateAnnotations(diRegistrationEntity);
            EffectEntityEntityType.CreateAnnotations(effectEntity);
            EffectObservationEntityEntityType.CreateAnnotations(effectObservationEntity);
            EntryPointEntityEntityType.CreateAnnotations(entryPointEntity);
            InvocationObservationEntityEntityType.CreateAnnotations(invocationObservationEntity);
            MethodObservationEntityEntityType.CreateAnnotations(methodObservationEntity);
            RunEntityEntityType.CreateAnnotations(runEntity);
            SourceFileEntityEntityType.CreateAnnotations(sourceFileEntity);

            AddAnnotation("ProductVersion", "10.0.8");
        }
    }
}
