// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Rig.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(RigDbContext), typeof(RigDbContextModel))]
